name: Sinquimia
favicon: null
layout_spectrum: 0
typography_spectrum: 0.55351
title: Droguería Sinquimia
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#34343f'
    - '#506d51'
    - '#131315'
    - '#ccded5'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
